#!/bin/sh
# Copyright 2026 Ammaar Ahmed
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -eu

: "${DASHBOARD_COMPOSE_FILE:?DASHBOARD_COMPOSE_FILE is required}"
: "${DASHBOARD_ENV_FILE:?DASHBOARD_ENV_FILE is required}"

exec docker compose \
  --env-file "${DASHBOARD_ENV_FILE}" \
  -f "${DASHBOARD_COMPOSE_FILE}" \
  --profile dashboard \
  up --detach --force-recreate exporter prometheus
